:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

# 構築

## 開発環境の構築

JavaScript 開発環境を構築するためには、以下の手順を実行してください。

### バージョンマネージャー

バージョンマネージャーを使用することで、異なるバージョンの Node.js を簡単に切り替えることができます。以下の手順でバージョンマネージャーをセットアップしてください。

#### バージョンマネージャーのセットアップ

1. NVM をインストールします。NVM は、Node.js のバージョンを管理するためのツールです。以下のコマンドを実行して、NVM をインストールしてください。

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
```

2. npm をインストールします。npm は、Node.js のパッケージマネージャーです。以下のコマンドを実行して、npm をインストールしてください。

```bash
nvm list
nvm install 16.10.1
npm -v
```

3. yarn をインストールします。yarn は、npm の代替となるパッケージマネージャーです。以下のコマンドを実行して、yarn をインストールしてください。

```bash
npm install -g yarn
yarn -v
```

4. ターミナルを再起動します。

#### トランスパイラ

トランスパイラを使用することで、ES6 以降の構文を ES5 に変換することができます。以下の手順でトランスパイラをセットアップしてください。

#### トランスパイラのセットアップ

1. package.json ファイルを作成します。以下のコマンドを実行して、package.json ファイルを作成してください。

```bash
npm init -y
```

-y オプションを指定することで、package.json ファイルの内容をデフォルト値で作成することができます。

1. Babel をインストールします。Babel は、トランスパイラの一つです。以下のコマンドを実行して、Babel をインストールしてください。

```bash
npm install --save-dev @babel/core @babel/cli @babel/preset-env
```

--save-dev オプションを指定することで、package.json ファイルの devDependencies にパッケージを追加することができます。

2. .babelrc ファイルを作成します。以下のコマンドを実行して、.babelrc ファイルを作成してください。

```bash
touch .babelrc
```

3. .babelrc ファイルに以下の内容を記述してください。

```json
{
  "presets": ["@babel/preset-env"]
}
```

#### トランスパイラの設定

1. package.json ファイルを開き、以下の内容を追加してください。

```json
{
  "scripts": {
    "build": "babel src -d dist"
  }
}
```

scripts には、npm コマンドを登録することができます。今回は、build コマンドを登録しています。build コマンドは、src ディレクトリの JavaScript ファイルをトランスパイルして、dist ディレクトリに出力するコマンドです。

#### トランスパイラの実行

1. src ディレクトリを作成して、index.js ファイルを作成します。

```JavaScript
// テンプレートリテラル
const name = 'John Doe';
const message = `Hello, ${name}!`;

// アロー関数
const add = (x, y) => x + y;

// デフォルトパラメーター
function greet(name = 'World') {
  console.log(`Hello, ${name}!`);
}

// 分割代入
const person = {
  firstName: 'John',
  lastName: 'Doe'
};

const { firstName, lastName } = person;

// スプレッド演算子
const arr = [1, 2, 3];
const arrCopy = [...arr];

// クラス
class Person {
  constructor(firstName, lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  getFullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}
```

2. 以下のコマンドを実行して、トランスパイルを実行してください。

```bash
npm run build
```

3. ES6 以降の構文が ES5 に変換されていることを確認してください。

```JavaScript
"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, _toPropertyKey(descriptor.key), descriptor); } }
function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
function _toPropertyKey(arg) { var key = _toPrimitive(arg, "string"); return _typeof(key) === "symbol" ? key : String(key); }
function _toPrimitive(input, hint) { if (_typeof(input) !== "object" || input === null) return input; var prim = input[Symbol.toPrimitive]; if (prim !== undefined) { var res = prim.call(input, hint || "default"); if (_typeof(res) !== "object") return res; throw new TypeError("@@toPrimitive must return a primitive value."); } return (hint === "string" ? String : Number)(input); }
// テンプレートリテラル
var name = 'John Doe';
var message = "Hello, ".concat(name, "!");

// アロー関数
var add = function add(x, y) {
  return x + y;
};

// デフォルトパラメーター
function greet() {
  var name = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'World';
  console.log("Hello, ".concat(name, "!"));
}

// 分割代入
var person = {
  firstName: 'John',
  lastName: 'Doe'
};
var firstName = person.firstName,
  lastName = person.lastName;

// スプレッド演算子
var arr = [1, 2, 3];
var arrCopy = [].concat(arr);

// クラス
var Person = /*#__PURE__*/function () {
  function Person(firstName, lastName) {
    _classCallCheck(this, Person);
    this.firstName = firstName;
    this.lastName = lastName;
  }
  _createClass(Person, [{
    key: "getFullName",
    value: function getFullName() {
      return "".concat(this.firstName, " ").concat(this.lastName);
    }
  }]);
  return Person;
}();
```

### モジュールバンドラー

モジュールバンドラーを使用することで、複数の JavaScript ファイルを一つのファイルにまとめることができます。以下の手順でモジュールバンドラーをセットアップしてください。

#### モジュールバンドラーのセットアップ

1. Webpack をインストールします。Webpack は、モジュールバンドラーの一つです。以下のコマンドを実行して、Webpack をインストールしてください。

```bash
npm install --save-dev webpack webpack-cli
npx webpack --version
```

npx コマンドは、npm パッケージを実行するためのコマンドです。npx コマンドを使用することで、ローカルにインストールされている npm パッケージを実行することができます。

2. webpack.config.js ファイルを作成します。以下のコマンドを実行して、webpack.config.js ファイルを作成してください。

```bash
touch webpack.config.js
```

3. webpack.config.js ファイルに以下の内容を記述してください。

```javascript
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js',
  },
};
```

4. package.json ファイルに以下の内容に変更してください。

```json
{
  "scripts": {
    "build": "webpack"
  }
}
```

#### モジュールバンドラーの実行

1. ./src/sample_es5.js ファイルを作成してください。

```JavaScript
function greeting(name) {
  return 'Hello ' + name;
}

module.exports = greeting;
```

2. ./src/index.js ファイルを変更してください。

```JavaScript
var greeting = require('./sample_es5');

console.log(greeting('ES5'));
```

3. 以下のコマンドを実行して、モジュールバンドラーを実行してください。

```bash
npm run build
```

4. ./dist/bundle.js ファイルが作成されていることを確認してください。

5. ./dist/bundle.js ファイルを実行してください。

```bash
node ./dist/bundle.js
```

#### モジュールバンドラーの設定

1. ./src/sample_es6.js ファイルを作成してください。

```JavaScript
class Greeting {
  constructor(name) {
    this.name = name;
  }
  say() {
    console.log(`Hello ${this.name}`);
  }
}

export default Greeting;
```

2. ./src/index.js ファイルを変更してください。

```JavaScript
var greeting = require('./sample_es5');
console.log(greeting('ES5'));

var greet = require('./sample_es6');
var g = new greet.default('ES6');
g.say();
```

3. 以下のコマンドを実行して、モジュールバンドラーを実行してください。

```bash
npm run build
```

4. ./dist/bundle.js ファイルが作成されていることを確認してください。

5. ./dist/bundle.js ファイルを実行してください。

```bash
node ./dist/bundle.js
```

6. 現状では ES6 のコードをそのまま出力しています。ES5 に変換するためには、babel-loader を使用します。 パッケージをインストールして webpack.config.js に以下のコードを変更してください。

```bash
npm install --save-dev babel-loader
```

```javascript
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
            },
          },
        ],
      },
    ],
  },
  target: ['web', 'es5'],
};
```

7. 以下のコマンドを実行して、モジュールバンドラーを実行してください。

```bash
npm run build
```

8. ./dist/bundle.js ファイルが作成されていることを確認してください。

9. ./dist/bundle.js ファイルを実行してください。

```bash
node ./dist/bundle.js
```

### TypeScript

TypeScript を使用することで、JavaScript に型を導入することができます。以下の手順で TypeScript をセットアップしてください。

#### TypeScript のセットアップ

1. TypeScript をインストールします。以下のコマンドを実行して、TypeScript をインストールしてください。

```bash
npm install --save-dev typescript @types/node
```

2. tsconfig.json ファイルを作成します。以下のコマンドを実行して、tsconfig.json ファイルを作成してください。

```bash
npx tsc --init
```

#### トランスパイラの設定

1. 必要なパッケージをインストールします。

```bash
npm install --save-dev @babel/preset-typescript @babel/plugin-proposal-class-properties typescript
```

2. .babelrc ファイルを変更します。

```bash
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

#### トランスパイラの実行

1. ./src/sample.ts ファイルを作成してください。

```TypeScript
class Greeting {
  constructor(public name: string) {}
  say() {
    console.log(`Hello ${this.name}`);
  }
}
```

2. ./src/index.ts ファイルを変更してください。

```TypeScript
import { Greeting } from "./sample";

const greeting = new Greeting("TypeScript");
greeting.say();
```

3. 以下のコマンドを実行して、トランスパイルを実行してください。

```bash
npx babel src --extensions '.ts,.tsx' --out-dir dist
```

4. ./dist/sample.js ファイルが作成されていることを確認してください。

5. ./dist/sample.js ファイルを実行してください。

```bash
node ./dist/index.js
```

#### モジュールバンドラーの設定

1. 必要なパッケージをインストールします。

```bash
npm install --save-dev ts-loader
```

2. webpack.config.js ファイルを開き、以下の内容を追加してください。

```javascript
module.exports = {
  mode: 'development',
  entry: './src/index.ts',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
            },
          },
        ],
      },
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
      },
    ],
  },
  target: ['web', 'es5'],
};
```

3. 以下のコマンドを実行して、モジュールバンドラーを実行してください。

```bash
npm run build
```

4. ./dist/bundle.js ファイルが作成されていることを確認してください。

5. ./dist/bundle.js ファイルを実行してください。

```bash
node ./dist/bundle.js
```

TypeScript ファイルをそのまま実行したい場合は、ts-node を使用します。

```bash
npm install --save-dev ts-node
```

動かし方は以下の通りです。

```bash
npx ts-node src/index.ts
```

### webpack-dev-server のセットアップ

webpack-dev-server を使用することで、開発中に自動的にビルドを実行し、ブラウザをリロードすることができます。以下の手順で webpack-dev-server をセットアップしてください。

#### webpack-dev-server のインストール

1. 以下のコマンドを実行して、webpack-dev-server をインストールしてください。

```bash
npm install --save-dev webpack-dev-server
```

#### webpack-dev-server の設定

1. webpack.config.js ファイルを開き、以下の内容を追加してください。

```javascript
const path = require('path');

module.exports = {
  //...
  devServer: {
    static: {
      directory: path.join(__dirname, 'public'),
    },
    compress: true,
    port: 9000,
  },
};
```

#### webpack-dev-server の実行

1. 以下のコマンドを実行して、webpack-dev-server を実行してください。

```bash
npx webpack serve
```

終了する場合は、Ctrl + C を押してください。

2. HTMLWebpackPlugin プラグインを使用して js ファイルに自動的にバンドルされた script タグを生成し、index.html に挿入できるようにします。

```bash
npm install --save-dev html-webpack-plugin
```

3. プロジェクト直下に index.html を作成してください。

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>App</title>
  </head>
  <body>
    <h1>アプリケーション</h1>
  </body>
</html>
```

4. webpack.config.js ファイルを開き、以下の内容を追加してください。

```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  // ...他のWebpack設定

  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.html',
    }),
  ],
};
```

5. package.json ファイルを開き、以下の内容を追加してください。

```json
{
  // ...他の設定
  "scripts": {
    "start": "webpack server --config ./webpack.config.js --open"
  }
}
```

6. 以下のコマンドを実行して、webpack-dev-server を実行してください。

```bash
npm start
```

7. ソースマップを有効にすることで、開発中にエラーが発生した場合に、エラーが発生したファイル名と行数を表示することができます。

```javascript
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

const env = process.env.NODE_ENV || "development";
const isDevelopment = env === "development";

module.exports = {
  mode: env,
  devtool: isDevelopment ? "source-map" : false,
```

8. TypeScript の型チェックを実行するために、tsconfig.json に以下の設定を追加してください。

```json
{
  "compilerOptions": {
    "sourceMap": true
  }
}
```

9. CSSサポートを追加します。

```
npm install --save-dev style-loader css-loader
```

`webpack.config.js`
```javascript
module.exports = {
  // ...他のWebpack設定

  module: {
    rules: [
      {
        test: /\.css/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              url: false,
              sourceMap: true,
            }
          }
        ]
      }
    ]
  }
};
```

`index.js`
```javascript
import "./style.css";
```


### テスティングフレームワークのセットアップ

テストを自動化することで、開発中に問題を早期に発見し、品質を向上させることができます。以下の手順でテスティングフレームワークをセットアップしてください。

#### Jest とは

Jest は、JavaScript のテスティングフレームワークです。以下の手順で Jest をセットアップしてください。

#### Jest のインストール

1. 以下のコマンドを実行して、Jest をインストールしてください。

```bash
npm install --save-dev jest
```

#### Jest の設定

1. package.json ファイルを開き、以下の内容を追加してください。

```json
{
  "scripts": {
    "test": "jest"
  }
}
```

2. ES Modules を私用している場合はテストが失敗するので以下の設定を package.json に追加する

```json
...
  "jest": {
    "moduleFileExtensions": [
      "js",
      "ts"
    ],
    "testMatch": [
      "**/**/*.test.js",
      "**/**/*.test.ts"
    ]
  }
}
```

#### TypeScript 対応

1. 以下のコマンドを実行して、必要なパッケージをインストールしてください。

```bash
npm install --save-dev @types/jest ts-jest
```

2. tsconfig.json ファイルを開き、以下の内容を追加してください。

```json
"module": "es2020",
```

#### テストの作成

1. テストファイルを作成してください。

`src/app.js`

```javascript
export function sum(a, b) {
  return a + b;
}
```

`src/app.test.js`

```javascript
import { sum } from './app.js';

test('adds 1 + 2 to equal 3', () => {
  const result = sum(1, 2);
  expect(result).toBe(3);
});
```

`src/app.ts`

```typescript
export function sum(a: number, b: number): number {
  return a + b;
}
```

`src/app.test.ts`

```typescript
import { sum } from './app';

test('adds 1 + 2 to equal 3', () => {
  const result = sum(1, 2);
  expect(result).toBe(3);
});
```

#### テストの実行

1. 以下のコマンドを実行して、テストを実行してください。

```bash
npm test
```

2. テストカバレッジを計測することで、テストがどの程度の範囲をカバーしているかを確認することができます。

```json
    "test": "jest --coverage"
```

### フォーマッタのセットアップ

フォーマッタを使用することで、コードのスタイルを統一し、読みやすくすることができます。以下の手順でフォーマッタをセットアップしてください。

#### Prettier とは

Prettier は、コードのフォーマットを自動化するツールです。以下の手順で Prettier をセットアップしてください。

#### パッケージのインストール

1. 以下のコマンドを実行して、Prettier をインストールしてください。

```bash
npm install --save-dev prettier
```

#### パッケージの設定

1. .prettierrc ファイルを作成し、以下の内容を記述してください。

```json
{
  "semi": true,
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 80,
  "tabWidth": 2
}
```

#### フォーマッタの実行

1. 以下のコマンドを実行して、フォーマッタを実行してください。

```bash
npx prettier --write .
```

2. package.json ファイルを開き、以下の内容を追加してください。

```json
{
  "scripts": {
    "format": "prettier --write ."
  }
}
```

### 開発ツールのセットアップ

開発ツールを使用することで、開発効率を向上させることができます。以下の手順で開発ツールをセットアップしてください。

#### パッケージのインストール

1. 以下のコマンドを実行して、開発ツールをインストールしてください。

```bash
npm install --save-dev @k2works/full-stack-lab
```

`./index.html` を以下の内容に変更します。

```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>App</title>
  </head>
  <body>
    <h1>アプリケーション</h1>
    <div id="app"></div>
    <div id="app-dev"></div>
  </body>
</html>
```

`./src/app.js` を以下の内容に変更します。

```javascript
console.log('app.js: loaded');
export class App {
  constructor() {
    console.log('App initialized');
  }
}

export function sum(a, b) {
  return a + b;
}
```

`./src/index.js` をルート直下に移動して以下の内容変更します。

```javascript
import { App } from './src/app.js';
const app = new App();

import render from "@k2works/full-stack-lab";
const contents = `
## 機能名
## 仕様
## TODOリスト
`;

const usecase = `
@startuml
left to right direction
actor "Actor" as ac
rectangle Application {
  usecase "UseCase1" as UC1
  usecase "UseCase2" as UC2
  usecase "UseCase3" as UC3
}
ac --> UC1
ac --> UC2
ac --> UC3
@enduml
`;

const uml = `
@startuml
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection
List <|-- AbstractList
Collection <|-- AbstractCollection
Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList
class ArrayList {
  Object[] elementData
  size()
}
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
annotation SuppressWarnings
@enduml
`;

const erd = `
@startuml
' hide the spot
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho
entity "Entity01" as e01 {
  *e1_id : number <<generated>>
  --
  *name : text
  description : text
}
entity "Entity02" as e02 {
  *e2_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}
entity "Entity03" as e03 {
  *e3_id : number <<generated>>
  --
  e1_id : number <<FK>>
  other_details : text
}
e01 ||..o{ e02
e01 |o..o{ e03
@enduml
`;
render({ contents, usecase, uml, erd });
`;
render({ contents, uml, erd });
```

2. TypScript も同様に変更してください。

importの部分は以下のように変更してください。

```javascript
const dev = require('@k2works/full-stack-lab');
...
dev.render({ contents, usecase, uml, erd });
```

3. 最後に不要なファイルを削除します。

#### 開発ツールの設定

1. webpack.config.js を以下の内容に変更します。

```javascript
...
  entry: './index.js',
...
```

#### 開発ツールの実行

1. 以下のコマンドを実行して、開発ツールを実行してください。

```bash
npm start
```