:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

# 配置

## GitHubとは
GitHubは、GitリポジトリをホストするためのWebベースのホスティングサービスです。GitHubを使用すると、コードを共有し、他の人と協力してプロジェクトを管理できます。

### GitHubのセットアップ
1. [GitHub](https://github.com/)にアクセスして、アカウントを作成します。
2. リポジトリを作成します。
3. リポジトリにコードをプッシュします。

## GitHub Actionsとは
GitHub Actionsは、GitHubでホストされる継続的インテグレーション/継続的デプロイメント（CI/CD）サービスです。GitHub Actionsを使用すると、コードの変更を自動的にビルド、テスト、デプロイできます。

### GitHub Actionsのセットアップ
1. リポジトリに`.github/workflows`ディレクトリを作成します。

2. ワークフローファイルを作成します。

`node.js.yml`を作成します。

```yml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
```

3. レポジトリにコミット・プッシュしてワークフローを有効にします。

4. READMEにバッジを追加します。

## Herokuとは
Herokuは、クラウドプラットフォームであり、開発者がアプリケーションを構築、実行、スケールするためのツールを提供します。

### Herokuにアプリをデプロイする手順
#### Heroku アカウントの作成
1. [Heroku](https://www.heroku.com/)にアクセスして、アカウントを作成します。

#### Heroku CLI のインストール
1. [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli)をダウンロードしてインストールします。

#### Heroku アプリケーションの作成
1. Herokuにログインします。
2. `heroku create`コマンドを実行して、新しいアプリケーションを作成します。

```bash
heroku create jip-episode00
```

3. HTTPサーバーを起動するために、パッケージをインストールして`Procfile`ファイルを作成します。

```bash
npm install http-server
```

```bash
web: npx http-server -p $PORT
```

package.jsonに以下の内容を追加します。

```json
"scripts": {
  ...
  "heroku-postbuild": "webpack --config ./webpack.config.js --progress"
  ...
},
```

#### アプリケーションのデプロイ
1. `git add .`コマンドを実行して、変更をステージングします。
2. `git commit -m "Initial commit"`コマンドを実行して、変更をコミットします。
3. `git push heroku master`コマンドを実行して、アプリケーションをデプロイします。

```bash
git push heroku episode/00:master
```

ここではmasterブランチ以外にもデプロイしています。

#### アプリケーションの起動
1. `heroku open`コマンドを実行して、アプリケーションを起動します。

## Vercelとは
Vercelは、サーバーレスのプラットフォームで、フロントエンドの開発者が簡単にWebサイトやアプリケーションをデプロイできるようにするものです。

### Vercelにデプロイする手順
以下は、Vercelにデプロイする手順です。

#### Vercelのサインアップ
まず、Vercelにサインアップする必要があります。Vercelには、GitHub、GitLab、Bitbucket、またはVercelのアカウントでサインアップできます。

#### ビルドコマンドの入力
次に、アプリケーションのビルドコマンドを入力する必要があります。ビルドコマンドは、アプリケーションをビルドするために必要なコマンドです。

#### 環境変数の設定(必要な場合)
必要に応じて、環境変数を設定することができます。環境変数は、アプリケーションで使用される変数です。

#### デプロイするブランチの選択
次に、デプロイするブランチを選択する必要があります。通常、デプロイするブランチは、masterブランチです。

#### デプロイの開始
最後に、デプロイを開始する必要があります。デプロイが完了すると、VercelはURLを提供します。

#### デプロイの確認
デプロイが完了したら、Webサイトやアプリケーションを確認することができます。

### VercelにCLIでデプロイする手順

1. Vercel CLIをインストールする
Vercel CLIをインストールするには、ターミナルで以下のコマンドを実行します。

```
npm install -g vercel
```

2. Vercelにログインする
Vercel CLIを使用するには、Vercelにログインする必要があります。以下のコマンドを実行して、Vercelにログインしてください。

```
vercel login
```

3. プロジェクトをデプロイする
webpack.config.jsのビルドファイルの出力先をpublicに変更します。

```javascript
 output: {
    path: __dirname + '/public',
    filename: 'bundle.js'
  },
```

Vercel CLIを使用して、プロジェクトをデプロイするには、以下のコマンドを実行します。

```
vercel
```